# Generated by Django 2.2.26 on 2024-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0004_auto_20170421_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
