# Generated by Django 2.2.26 on 2024-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0005_student_exam_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='exam_card',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
